<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rest_image_service"
 *
 * Auto generated by Extension Builder 2017-02-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'REST Image Service',
	'description' => 'Service to retrieve images in different sizes',
	'category' => 'services',
	'author' => 'Andreas Thurnheer-Meier, Daniel Corn',
	'author_email' => 'tma@iresults.li, cod@iresults.li',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);